### ISSUE TITLE
Add telephone validation in the form

### ISSUE THREAD

**Issue by kaisaf** [kaisaf/gearcircles#45]

**Comment by vmenezes** [comment]
twilio_helper.py has a validate_number method that you may use for that

**Comment by vmenezes** [comment]
create endpoint to send validation code and save the same in the session.
create endpoint to validate phone code delete it from session and save new phone in DB.
the POST method of the form should not be executed if a code still exist on session.

**Comment by kaisaf** [comment]
url /get-sms-code, view CreateCodeView,  helper function def generate_code

When user changes the phone number, a button shows up that says "get validation code" and the rest of the form is disabled. On click to that button, an ajax call is made to the CreateCodeView. CreateCodeView calls the helper function, sends a sms with the returned code to the user and saves the code to the session. The button is replaced with an empty form field and a button with text "validate code".  

User types in the code and clicks validate code. ValidateCodeView then compares the code user sent to the code saved in the session. If the code is the same, code in the session is deleted, phone number saved in the db and the rest of the form opened for the user to fill out. If the code is not correct, user will receive an error message.
