### ISSUE TITLE
Change index page

### ISSUE THREAD

**Issue by vmenezes** [kaisaf/gearcircles#55]
Index page should not have login option until the product is launched, a /demo may be created for that.
The new index should generate points randomly, not using DB.

**Comment by kaisaf** [comment]
https://github.com/kaisaf/gearcircles/pull/56

**Comment by kaisaf** [comment]
gmaps.js: in showmap function add position to callback as a parameter 
index.js: replace getLocations with createLocations so that points are generated randomly based on position gotten from gmaps.js showmap function
